"""Initial migration

Revision ID: eb05e96de889
Revises: 
Create Date: 2022-07-27 11:36:56.312399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb05e96de889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('fuel', sa.String(length=50), nullable=True))
    op.add_column('car', sa.Column('motor', sa.String(length=50), nullable=True))
    op.add_column('car', sa.Column('register', sa.String(length=50), nullable=True))
    op.add_column('car', sa.Column('brand', sa.String(length=50), nullable=True))
    op.add_column('car', sa.Column('gearbox', sa.String(length=50), nullable=True))
    op.alter_column('car', 'image_file',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'image_file',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('car', 'gearbox')
    op.drop_column('car', 'brand')
    op.drop_column('car', 'register')
    op.drop_column('car', 'motor')
    op.drop_column('car', 'fuel')
    # ### end Alembic commands ###
